[build]
  # Répertoire de publication (racine du site)
  publish = "."
  
  # Commande de build (pas nécessaire pour site statique)
  command = "echo 'Site statique déployé avec succès'"

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "18"

# Configuration des redirections et réécritures
[[redirects]]
  # Redirection du domaine www vers non-www
  from = "https://www.autoflowpro.netlify.app/*"
  to = "https://autoflowpro.netlify.app/:splat"
  status = 301
  force = true

[[redirects]]
  # Redirection pour SPA (si nécessaire plus tard)
  from = "/*"
  to = "/index.html"
  status = 200

# Headers pour la sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
    # Performance
    Cache-Control = "public, max-age=86400"
    
    # CORS pour les formulaires
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache plus long pour les assets statiques
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Configuration des formulaires Netlify
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuration des fonctions (pour usage futur)
[functions]
  directory = "netlify/functions"

# Configuration du déploiement
[context.production.environment]
  NODE_ENV = "production"
  GATSBY_ACTIVE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Configuration des notifications de formulaires
[build.processing.images]
  compress = true

# Plugin Netlify pour l'optimisation
[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

# Configuration avancée pour le SEO
[build.environment]
  # Variables pour le tracking
  GOOGLE_ANALYTICS_ID = "GA_TRACKING_ID"
  FACEBOOK_PIXEL_ID = "FB_PIXEL_ID"
  LINKEDIN_INSIGHT_TAG = "LINKEDIN_TAG_ID"

# Configuration des branches
[context.main]
  command = "echo 'Déploiement production'"

[context.develop]
  command = "echo 'Déploiement développement'"

# Configuration Edge Functions (pour des fonctionnalités avancées)
[[edge_functions]]
  function = "hello"
  path = "/api/hello"